"""Adicionar novos campos em Relatorio e FotoRelatorio conforme especificacao tecnica

Revision ID: fe8e8e8ec755
Revises: cc5ad1eaca6b
Create Date: 2025-11-02 02:42:45.150055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8e8e8ec755'
down_revision = 'cc5ad1eaca6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos_relatorio', sa.Column('url', sa.Text(), nullable=True))
    op.alter_column('fotos_relatorio', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('fotos_relatorio', 'legenda',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('fotos_relatorio_relatorio_id_fkey'), 'fotos_relatorio', type_='foreignkey')
    op.create_foreign_key(None, 'fotos_relatorio', 'relatorios', ['relatorio_id'], ['id'], ondelete='CASCADE')
    op.add_column('relatorios', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('relatorios', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.add_column('relatorios', sa.Column('local', sa.String(length=255), nullable=True))
    op.add_column('relatorios', sa.Column('observacoes_finais', sa.Text(), nullable=True))
    op.add_column('relatorios', sa.Column('criado_por', sa.Integer(), nullable=True))
    op.add_column('relatorios', sa.Column('atualizado_por', sa.Integer(), nullable=True))
    op.alter_column('relatorios', 'lembrete_proxima_visita',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='lembrete_proxima_visita::timestamp')
    op.create_foreign_key(None, 'relatorios', 'users', ['criado_por'], ['id'])
    op.create_foreign_key(None, 'relatorios', 'users', ['atualizado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relatorios', type_='foreignkey')
    op.drop_constraint(None, 'relatorios', type_='foreignkey')
    op.alter_column('relatorios', 'lembrete_proxima_visita',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('relatorios', 'atualizado_por')
    op.drop_column('relatorios', 'criado_por')
    op.drop_column('relatorios', 'observacoes_finais')
    op.drop_column('relatorios', 'local')
    op.drop_column('relatorios', 'categoria')
    op.drop_column('relatorios', 'descricao')
    op.drop_constraint(None, 'fotos_relatorio', type_='foreignkey')
    op.create_foreign_key(op.f('fotos_relatorio_relatorio_id_fkey'), 'fotos_relatorio', 'relatorios', ['relatorio_id'], ['id'])
    op.alter_column('fotos_relatorio', 'legenda',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('fotos_relatorio', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('fotos_relatorio', 'url')
    # ### end Alembic commands ###