"""add_fcm_token_to_users

Revision ID: 3d4ec2dfeefe
Revises: 20251029_2300
Create Date: 2025-10-30 19:34:22.768244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4ec2dfeefe'
down_revision = '20251029_2300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###