"""Add ChecklistObra and ProjetoChecklistConfig models

Revision ID: 42776d8c4e78
Revises: 001
Create Date: 2025-09-20 15:18:35.204621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42776d8c4e78'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_report_number_per_project'), 'relatorios', type_='unique')
    op.drop_column('relatorios', 'numero_relatorio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relatorios', sa.Column('numero_relatorio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('unique_report_number_per_project'), 'relatorios', ['projeto_id', 'numero_relatorio'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###